### ISSUE TITLE
ID of the wallpaper is always #0

### ISSUE THREAD

**Issue by vignedev** [berwyn/muzei-ponies#3]
![screenshot_2016-06-30-12-22-32](https://cloud.githubusercontent.com/assets/18449733/16485186/beae16ac-3ebd-11e6-8be1-51184a1b117b.png)
The picture should talk for itself. I suspect it has something to do with the upgraded API I heard few days ago. The image is still downloading and displaying correctly, the ID of it is incorrect.

**Comment by berwyn** [comment]
Just having a quick look over the API docs doesn't show any changes that should lead to that, but I'll have a look at it tonight. Thanks for the report!

**Comment by vignedev** [comment]
I've figured out how to fix it:

Replace `image.idNumber` with `image.id` everywhere.
Remove this from `DerpibooruResult.java`.

``` java
@SerializedName("id_number")
public long   idNumber;
```

**Comment by berwyn** [comment]
:+1: 
Looks like that works. I'll dig out my keystore and get a release out this weekend.

**Comment by berwyn** [comment]
Fixed in 1.1.0 (f56750b)

**Comment by berwyn** [comment]
Also, you can opt in to beta and make sure everything works there, I'll probably push it up to the live channel soon-ish
